baseURL: https://abnvanand.github.io/
languageCode: en-us
title: The Tech Underbelly
theme: PaperMod
taxonomies:
  category: categories
  tag: tags
  series: series

##### theme hugo-PaperMod configs
params:
  defaultTheme: auto # to switch between dark or light according to browser theme
  ShowCodeCopyButtons: true

# Add search page https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
  - HTML
  - RSS
  - JSON # is necessary
