baseURL: https://abnvanand.github.io/
languageCode: en-us
title: The Tech Underbelly
theme: PaperMod
taxonomies:
  category: categories
  tag: tags
  series: series

##### theme hugo-PaperMod configs
params:
  defaultTheme: auto # to switch between dark or light according to browser theme
  ShowCodeCopyButtons: true

# Add search page https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
  - HTML
  - RSS
  - JSON # is necessary

# Add custom menu items.
# Source: https://github.com/adityatelange/hugo-PaperMod/issues/129#issuecomment-744309373
menu:
  main:
  - identifier: tags
    name: tags
    url: /tags/
    weight: 20
  - identifier: categories
    name: categories
    url: /categories/
    weight: 10
  # - identifier: series
  #   name: series
  #   url: /series/
  #   weight: 10
  - identifier: archives
    name: archives
    url: /archives/
    weight: 30
  - identifier: search
    name: search
    url: /search/
    weight: 40
